### ISSUE TITLE
Commit fc8b0e5 (randomization ~) breaks config file

### ISSUE THREAD

**Issue by Seanst3r** [cronie-crond/cronie#102]
Hi. After cloning the latest git version my crontab won't install.  The last commit is this one:

Add random within range '~' operator …
@opohorel opohorel committed on Nov 8, 2021

I get "bad minute", bad "hour", bad day-of-week, you name it.

01 * * * * /bin/echo Hello, world!

crontab: installing new crontab
"/tmp/crontab.ZlLH9I":73: bad minute

I reverted to the prior commit it seems back to normal.

git reset --hard 19c2e1deb47b2fd9fb0e4ac3667bebc06d86174d

**Comment by t8m** [comment]
Please try the current master branch (https://github.com/cronie-crond/cronie/commit/07bf4b9037de19b580cfa24f5ad023b56725b285)

**Comment by Seanst3r** [comment]
Ok, I touched my crontab and it installed ok. I can't tell you if it has interpreted it all correctly.. time will tell as my entries fire off but I would assume it will be fine.

As an aside, it's pretty cool that you folks are here maintaining this thing that's been a staple for decades. The fact that someone cared enough to create and share a new feature like this is pretty awesome. I'll be sure to put it to use.

**Comment by t8m** [comment]
@Seanst3r please retest with the latest checkout.
