### ISSUE TITLE
file /etc/cron.d from install of cronie-1.4.11-24.el7_9.x86_64 conflicts with file from package

### ISSUE THREAD

**Issue by MW-algo** [cronie-crond/cronie#103]
Hi, 
I updated to the last cronie package from cronie-1.4.11-23.el7.x86_64.
I get this message in the yum update.
file /etc/cron.d from install of cronie-1.4.11-24.el7_9.x86_64 conflicts with file from package <my package that uses crond>

Looked through the commit and couldn't find any change that is related.
Any idea what I'm doing wrong.
I ran the same thing on the same env since cronie-1.4.11-19.el7.x86_64 without an issue.

**Comment by t8m** [comment]
I am sorry but this issue tracker does not track issues with Red Hat Enterprise Linux or CentOS rpm packages. You'll have to report the issue at Red Hat Bugzilla.
