### ISSUE TITLE
Add switch `-f` for foreground mode

### ISSUE THREAD

**Issue by paulmenzel** [cronie-crond/cronie#104]
Ubuntu’s `cron` has [the switch `-f`](https://manpages.ubuntu.com/manpages/impish/en/man8/cron.8.html):

> -f      Stay in foreground mode, don't daemonize.

To use cronie’s cron(d) as a drop-in replacement, it’d be great if that switch could be supported, and not result in `crond: invalid option -- 'f'`.

**Comment by YoruStar** [comment]
cronie’s cron(d) has the switch -n :

> -n  run in foreground

you can see it in `/usr/sbin/crond -h` , I think it's the same as -f，

**Comment by paulmenzel** [comment]
Yes, so should an alias be added, so it can be used as a drop-in replacement?
