### ISSUE TITLE
sox not play sound with cronie

### ISSUE THREAD

**Issue by superiums** [cronie-crond/cronie#105]
I have this command in my task.sh
```
play -q "mysound.ogg" &
```

it use sox to play a sound. it works alonely will, but in cronie it not play. 
i've tried to set env DBUS_SESSION_BUS_ADDRESS='unix:path=/run/user/1000/bus', but not help.

------------
cronie 1.5.7
in Arch

**Comment by t8m** [comment]
This can have various reasons. One being file system namespacing so the cronie spawned process does not see the right files/sockets.

**Comment by superiums** [comment]
is there any way to tell the system namespacing to recognize my file ?

**Comment by t8m** [comment]
I'd suggest you to try to find help in other forums such as for pulseaudio users or others. This is really not a cronie related issue but rather an issue of trying to use the sound subsystem on linux from a different login session than the current one.

**Comment by superiums** [comment]
thanks
