### ISSUE TITLE
Day of week range broken in 1.6.0?

### ISSUE THREAD

**Issue by a-dekker** [cronie-crond/cronie#107]
After compiling and installing the new release 1.6.0, all of a sudden my day-of-week range of "1-5" is marked as invalid.

`1 16 * * 1-5 /usr/local/bin/do_exec.sh`

```
"/tmp/crontab.4rnM13":62: bad day-of-week
Invalid crontab file, can't install.
```
reverting to 1.5.7 and the error message is gone. Is something wrong on my side, or is a bug introduced?

**Comment by YoruStar** [comment]
in the funtion `static int get_range()` 

> `case R_RANGE` need `unget_char(ch, file)`, just like `case R_RANDOM`.

```
case R_RANGE:
    unget_char(ch, file);
    if (get_number(&num2, low, names, file) != EOF) {
        state = R_RANGE_NUM2;
        break;
    }
    return (EOF);
```
the reason of this issue is the same as [#102](https://github.com/cronie-crond/cronie/issues/102)
