### ISSUE TITLE
cronie appears to run spontaneously

### ISSUE THREAD

**Issue by mauricev** [cronie-crond/cronie#110]
I’ve been noticed duplicates of files after cronie runs in the middle of the night. So I made a test and sure enough, cronie runs in response to my crontab and it runs a second time, on its own executing the programs in /etc/cron.daily. When I deleted my crontab, it still ran what was in cron.daily. What’s triggering it to run on its own apparently?

**Comment by t8m** [comment]
What do you mean by "my crontab"? There are various crontabs that are parsed and handled by cronie.
Please see the manual page crond(8).

**Comment by mauricev** [comment]
/etc/crontab is the sole crontab on my system to my knowledge. Are you suggesting there is a hidden crontab somewhere?

**Comment by t8m** [comment]
There is nothing in /etc/cron.d/ ?

**Comment by mauricev** [comment]
Interestingly, there is, a file named 0hourly. Its content is
```
# Run the hourly jobs
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root
01 * * * * root run-parts /etc/cron.hourly
```
Which I assume means it will trigger the scripts in /etc/cron.hourly. However, the scripts in there aren’t the ones being duplicated. They’re in /etc/cron.daily. 

Here is a system showing when they're running
```
I ran at 2022.04.02-03.13.36
I ran at 2022.04.02-03.53.32
I ran at 2022.04.03-03.14.04
I ran at 2022.04.03-03.20.38
I ran at 2022.04.04-03.13.32
I ran at 2022.04.04-03.33.33
I ran at 2022.04.05-03.15.29
I ran at 2022.04.05-03.15.29
I ran at 2022.04.06-03.13.24
I ran at 2022.04.06-03.25.04
I ran at 2022.04.07-03.13.32
I ran at 2022.04.07-03.44.11
```

**Comment by t8m** [comment]
If you look into cron.hourly, you'll see something more there.
Most probably anacron is being run there and then anacron executes things from crond.daily.

**Comment by mauricev** [comment]
A-ha! Anacron is indeed there and the /etc/anacrontab does indeed run all the cron scripts. Thank you for figuring that out!
