### ISSUE TITLE
Time range not working

### ISSUE THREAD

**Issue by uwe-007** [cronie-crond/cronie#111]
I'm using cronie 1.6.0 (Termux).
If I set a time range for a job in my crontab like minute 10-20, the cron job will never run.
If I write for example "10,20,30" it works.

**Comment by uwe-007** [comment]
Some feedback would be nice.
Can someone confirm this bug or am I the only one with it?

**Comment by t8m** [comment]
Yes, this is a known bug fixed in the git tree. I'll do a new release.

**Comment by uwe-007** [comment]
thx
