### ISSUE TITLE
What if both anacron and noanacron are installed?

### ISSUE THREAD

**Issue by jackhhh** [cronie-crond/cronie#112]
There is no conflict defined in the spec file between the two packages. What will happen if a user installed both two packages? Is it necessary to add a conflict in the spec file to avoid this situation?

**Comment by t8m** [comment]
The cronie-anacron will take precedence and the anacron will be used to run the jobs. The jobs run from the cronie-noanacron will be just no-ops as they check for presence of the 0anacron file before executing the jobs.
