### ISSUE TITLE
option to allow anacron jobs on battery

### ISSUE THREAD

**Issue by fgozzini** [cronie-crond/cronie#114]
Currently daily (weekly, monthly) anacron jobs are not run on battery. It would be nice to have a way of enabling that without modifying the `/etc/cron.hourly/0anacron` script explicitly. For example reading the value `ANACRON_RUN_ON_BATTERY_POWER=yes` in the file `/etc/default/anacron` as found in some old online post.

**Comment by t8m** [comment]
Would you like to submit a pull request?

**Comment by fgozzini** [comment]
I submitted a pull request. I am no expert in bash scripting but I found no issues with testing locally a similar script on my laptop.
