### ISSUE TITLE
START_HOURS_RANGE

### ISSUE THREAD

**Issue by ftigges-comdev** [cronie-crond/cronie#122]
Hi,
I am trying to set the allowed time range to sth. like 7 PM to 7 AM (aka non-workhours)

As far as I can tell, this isn't possible.

            if (range_stop < range_start) {
                range_start = 0; range_stop = 0;
                goto reg_invalid;
            }

This use case doesn't look to outlandish to me.. 
S do I miss sth. obvious?

Thanks

**Comment by andrewtimberlake** [comment]
Try this: `0 0-7,19-23 * * *` -> on the hour every hour from midnight to 7am and from 7pm to midnight

**Comment by ftigges-comdev** [comment]
Hi, thanks for your reply.

My question is about /etc/**anachron**tab, hence the START_HOURS_RANGE.
I apologize for the bad ticket quality.

As a workaround I am doing:

```
START_HOURS_RANGE=20-24
#period in days   delay in minutes   job-identifier   command
1       5       cron.daily              sleep $[ $RANDOM % 7 ]h; nice /usr/lib/cron/run-crons /etc/cron.daily
```

**Comment by t8m** [comment]
Yeah, unfortunately doing this in anacron is not possible. Your workaround is supposedly the best you can do.
