### ISSUE TITLE
N00bs try cron on Arch EndeavourOS

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [cronie-crond/cronie#123]
I don't understand why it doesn't work :

I do `sudo crontab -e`

It opens a blank nano page, then I fill the command 

`* * * * * alacritty`

Nothing happen

**Comment by gnuhead-chieb** [comment]
Cron is not designed for running GUI applications.
You need to do workaround for running GUI application from cron jobs.

First, run `echo $XAUTHORITY $DISPLAY` on your session.
In my case, this outputs `/run/user/1000/xauth_TeTWzm :1`
**This output result depends on your environment**

In this case, you have to configure cron setting like this `* * * * * XAUTHORITY=/run/user/1000/xauth_TeTWzm DISPLAY=:1 alacritty`

**Comment by gnuhead-chieb** [comment]
Did you solve the problem?

**Comment by jojojojojoj5564656465465** [comment]
i did 
sudo nano crontab -e and past

* * * * * XAUTHORITY=/run/user/1000/xauth_TeTWzm DISPLAY=:1 alacritty

* * * * * XAUTHORITY=/home/manjaro/.Xauthority DISPLAY=:0 alacritty
Didn't work but i think it's because of arch

**Comment by gnuhead-chieb** [comment]
try without sudo

**Comment by jojojojojoj5564656465465** [comment]
![image](https://user-images.githubusercontent.com/45184918/215345166-3f961393-dd12-42c3-8f01-3756daf62fa0.png)

I cannot write if i am wihout sudo

**Comment by gnuhead-chieb** [comment]
sudo crontab -e -u [username]

**Comment by jojojojojoj5564656465465** [comment]
![image](https://user-images.githubusercontent.com/45184918/215345804-a37d3efe-27b8-458a-953b-a61517bf5572.png)
 
i also did systemctl enable --now cronie.service after still not work

**Comment by jojojojojoj5564656465465** [comment]
![image](https://user-images.githubusercontent.com/45184918/215346572-c88e02db-cc2a-4ca2-8e66-8ade0f7a0551.png)


Works but doesn't open my zsh terminal
