### ISSUE TITLE
Failed to execute crontab command without parameters through ssh

### ISSUE THREAD

**Issue by YoruStar** [cronie-crond/cronie#131]
execute crontab command without parameters through ssh, It will get stuck
```
ssh root@xxx.xxx.xxx.xxx crontab
```
but execute the crontab command directly, it will success
```
[root@localhost ~]# crontab
crontab: usage error: file name or - (for stdin) must be specified
    ... ...
```
I found that in the code, it made a special judgment on the command from the stdin
```
else if (isatty(STDIN_FILENO)) {
    usage("file name or - (for stdin) must be specified");
}
```
Could you tell me why you design this way?

**Comment by t8m** [comment]
The crontab command historically takes the input from stdin. When called from terminal we have an option to change this behavior. Not so in other cases because it can be called from scripts and we do not want to break them.

So no, this behavior is not a bug and won't be changed.

**Comment by YoruStar** [comment]
> The crontab command historically takes the input from stdin. When called from terminal we have an option to change this behavior. Not so in other cases because it can be called from scripts and we do not want to break them.
> 
> So no, this behavior is not a bug and won't be changed.

Thank you for your answer
