### ISSUE TITLE
[Question]: how to change the home directory while creating cronjob?? If my file was in different directory then cron runs on home directory??

### ISSUE THREAD

**Issue by vishnumur777** [cronie-crond/cronie#132]
`Log File`

From root@localhost.localdomain  Sun Jan  1 23:13:01 2023
Return-Path: <root@localhost.localdomain>
X-Original-To: root
Delivered-To: root@localhost.localdomain
Received: by localhost.localdomain (Postfix, from userid 0)
        id 94FCB262A32; Sun,  1 Jan 2023 23:13:01 +0530 (IST)
From: "(Cron Daemon)" <root@localhost.localdomain>
To: root@localhost.localdomain
Subject: Cron <root@VISHNULAP> export . /root/.profile; /root/bashPractice/insert.sh
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=c220>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus>
X-Cron-Env: <XDG_SESSION_TYPE=unspecified>
X-Cron-Env: <XDG_SESSION_CLASS=background>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Message-Id: <20230101174301.94FCB262A32@localhost.localdomain>
Date: Sun,  1 Jan 2023 23:13:01 +0530 (IST)

/root/bashPractice/insert.sh: line 3: ./content.sh: No such file or directory
cat: '*.n': No such file or directory

**Comment by t8m** [comment]
You cannot change the directory where the command from crontab is run at. But that's no problem, you can do that in the command itself.
```
* * * * * cd /whatever/directory ; yourscript
```

**Comment by vishnumur777** [comment]
Thank you @t8m
