### ISSUE TITLE
Range over midnight?

### ISSUE THREAD

**Issue by guettli** [cronie-crond/cronie#15]
I could not see in the current docs if ranges over midnight are valid or not.

I would like to read in "man 5 crontab" if this is valid or not:

`05 22-5 * * * my_command.
`

Does `22-5` expand to `22,23,0,1,2,3,4,5`?
Here are the current docs: https://github.com/cronie-crond/cronie/blob/master/man/crontab.5#L197

Please forgive me, if I was blind.

**Comment by t8m** [comment]
No, in the range the first number must always be lower or equal to the second. I've fixed the docs.
