### ISSUE TITLE
Ranges broken once again in 1.7.0?

### ISSUE THREAD

**Issue by a-dekker** [cronie-crond/cronie#158]
https://github.com/cronie-crond/cronie/issues/107 seems to be back in 1.7.0?

If so, would it be an idea to setup tests to avoid issues like this for a primary/important tool like this?

**Comment by t8m** [comment]
Unfortunately I do not have time to work on a test suite. It would be of course nice to have it. I assume it would require adding quite some special plugging to avoid the need to set fake time on the test machine.

**Comment by t8m** [comment]
Are you sure about the ranges being broken? Do you see exactly the same failure as in #107 or anything else?

**Comment by a-dekker** [comment]
> Unfortunately I do not have time to work on a test suite. It would be of course nice to have it. I assume it would require adding quite some special plugging to avoid the need to set fake time on the test machine.

Just test cases for valid crontab entries would be something imho.

**Comment by a-dekker** [comment]
> Are you sure about the ranges being broken? Do you see exactly the same failure as in #107 or anything else?
I saw the same thing. But since there are not more reports I am afraid it could be something messed up on my side. Will do more tests and report back.

**Comment by a-dekker** [comment]
I can confirm it is indeed my fault. For https://github.com/cronie-crond/cronie/issues/107, I created my own temporary patch, but forgot to remove this part, which caused this unwanted side effect.

Will close this issue as it is invalid.
