### ISSUE TITLE
cronie 1.7.0 sends error emails "/etc/default/anacron: No such file or directory"

### ISSUE THREAD

**Issue by sbraz** [cronie-crond/cronie#159]
Hi,
As reported in https://bugs.gentoo.org/915724, since b53221ff55cbb4b13520472b75b0fd9028940534, 0anacron attempts to source a non-existing file because no `/etc/default/anacron` gets installed.
It sends this kind of errors by email:
```
/etc/cron.hourly/0anacron: line 11: /etc/default/anacron: No such file or directory
run-parts: /etc/cron.hourly/0anacron exited with return code 1
```
I'm pinging @fgozzini who authored the commit. It would be nice to restore the `test -r` check that was present in the first version of #115.

**Comment by sbraz** [comment]
I've offered a fix in #160.

**Comment by t8m** [comment]
I've merged the other PR as I've read it first in the list of PRs. Thank you for your bug report and fix anyway.

**Comment by sbraz** [comment]
No problem, adding the commit here for reference: 7700b1465d32ddb1d3988e9af852af6f0f5cd66e.
