### ISSUE TITLE
Option to disable backup files?

### ISSUE THREAD

**Issue by auouymous** [cronie-crond/cronie#167]
#128 added the creation of backup files, but doesn't appear to give the user or system admin any way to disable them. I have the files tracked by git and had to patch cronie to disable the backups. Would it be possible to add options to disable backups per-user or system wide?

**Comment by t8m** [comment]
You could use .gitignore to ignore these backup files.

But yeah, adding an option to disable them would be possible.

**Comment by ileGITimo** [comment]
Second this

**Comment by t8m** [comment]
Fixed by @ileGITimo, thank you.
