### ISSUE TITLE
Anacron does not support MAILFROM

### ISSUE THREAD

**Issue by mlazze** [cronie-crond/cronie#17]
Unless I'm missing something obvious, MAILFROM works correctly in a crontab, but it gets ignored in an anacrontab.

Crontab example:
```
MAILTO=to@example.com
MAILFROM=from@example.com
*  *  *  *  *  echo "error" 1>&2
```
This correctly sets From Header to `from@example.com`.

While
Anacrontab example:
```
MAILTO=to@example.com
MAILFROM=from@example.com
@daily       5       test              echo "error" 1>&2
```
This has From Header set to `Anacron <root>`.

Problem is, gmail blocks anacron email with reason `'From' header has non compliant domain name`.

Mails are sent using sendmail, which is symlinked to msmtp.

Is Anacron supposed to ignore MAILFROM?

**Comment by t8m** [comment]
Yes, the support for MAILFROM in anacron is missing.

**Comment by lkraav** [comment]
@t8m is `MAILFROM` supposed to substitute environment variables?

`MAILFROM=cron+$USER` currently doesn't seem to be substituted.

**Comment by t8m** [comment]
No, unfortunately not.

**Comment by t8m** [comment]
PRs welcome :)
