### ISSUE TITLE
Contributing simple Linux CI based on GitHub Actions welcome?

### ISSUE THREAD

**Issue by hartwork** [cronie-crond/cronie#174]
Hi!

I noticed that this repository does not have any CI so that currently pull requests could in theory break compilation unnoticed any time even with careful review. Use of GitHub Actions would be free of cost for you, works well, and only requires addition of a single YAML file to activate. I'm thinking of an approach similar to https://github.com/projectM-visualizer/frontend-libvisual-plug-in/blob/master/.github/workflows/linux.yml , aiming to cover at least GCC 13 and Clang 17 here. What do you think? 

Best, Sebastian

**Comment by t8m** [comment]
Yeah, sure. The biggest problem is we do not have any tests. But even just building the sources would be useful as a CI job.
