### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by hannob** [cronie-crond/cronie#180]
The last release (1.7.1) is still affected by the issues described in #170.

Can we get a new release to get the fixes out in a release?

**Comment by djc** [comment]
Yes, please -- I just went on a deep dive to figure out why I haven't been receiving emails from cron for a few months now, and it turns out there was a regression, which was fixed a week after release but then the fix hasn't been released.

**Comment by t8m** [comment]
The 1.7.2 version was released today.

**Comment by djc** [comment]
Thanks for the quick response!
