### ISSUE TITLE
don't depend on vi

### ISSUE THREAD

**Issue by ilf** [cronie-crond/cronie#19]
Using `crontab -e` without `vi` installed results in the error: `/bin/sh: /usr/bin/vi: No such file or directory`.
Please don't hard-depend on vi. As fallback, it's sane. But please prefer my setting in `$EDITOR`. Thanks.

**Comment by t8m** [comment]
Which version of cronie do you have? The current version already respects $EDITOR if set.

**Comment by ilf** [comment]
Running cronie 1.5.1.

You're right, $EDITOR is respected. Just not with something like `sudo crontab -u nobody -e`, there is uses vi. But `crontab -u nobody -e` in a root-shell uses $EDITOR. Must be something about env with sudo.

Sorry for the noise.

**Comment by t8m** [comment]
Yes, sudo clears such environment variables for security reasons.
