### ISSUE TITLE
Continuation in cronie's crontab?

### ISSUE THREAD

**Issue by seamusdemora** [cronie-crond/cronie#194]
Pls excuse the awkward wording of the title, but I have a simple question:

I've read issues #54 and #55. Can some tell me if one is allowed to use line continuation in cronie's crontab? IOW,  is there a way to split a single command line onto multiple lines?

If so, is the backslash `\` used as the line continuation character? 

Final question: I'm a Debian user. There is no available `cronie` package for Debian (stable). Any cautions or warnings re building & using cronie on my system?

**Comment by t8m** [comment]
No, unfortunately it is not possible to use `\` as a continuation character at the EOL in crontabs.

As for using cronie on Debian - I do not know, I assume it should work fine there but I did not test it.

**Comment by seamusdemora** [comment]
@t8m ,  Thank you for the information.
