### ISSUE TITLE
Multiple instances of crond may be launched

### ISSUE THREAD

**Issue by Dormouse759** [cronie-crond/cronie#22]
When crond is launched using systemd, one more instance may be launched using /usr/sbin/crond.
This is because of change at: https://github.com/cronie-crond/cronie/commit/5b285b46b88dc63689c6a56542cb2ba81f861b66
When crond launches, it checks whether it already runs or not by looking at the pid file at /var/run/, but this no longer is a correct way of checking for another instance.

**Comment by t8m** [comment]
I do not think this is a real issue. Running /usr/sbin/crond manually is a debugging thing and there is no point in limiting that in any way. Or, if you think otherwise, please propose how this should be really handled.

**Comment by Dormouse759** [comment]
I also don't see any problem in launching the daemon manually. I see potential problems with having the daemon running twice at the same moment.
It hasn't been allowed until the mentioned commit to have multiple instances running at once and it seemed quite intentional.
I propose checking for other instances, should another instance be detected, then to terminate the process and log an error.
If a specific proposal of handling this is required, I can prepare a pull request.

**Comment by Dormouse759** [comment]
I'd suggest using pidof.
If pidof crond returns more than one pid, it means multiple instances are running.

**Comment by t8m** [comment]
You mean spawning pidof from crond? Please no. I really do not think this guard is needed. If someone is starting crond manually he should know what he is doing. He should know that he might need to shutdown the crond.service, etc.

**Comment by Dormouse759** [comment]
Thank you for the explanation, I am closing this issue.
