### ISSUE TITLE
MAILFROM should probably substitute variables

### ISSUE THREAD

**Issue by lkraav** [cronie-crond/cronie#26]
https://github.com/cronie-crond/cronie/issues/17#issuecomment-447818294

Because hardened mail servers will refuse to accept mail without authentication, it would make sense to provide `MAILFROM` with the ability to substitute at least `$USER` variable.

Global configuration `MAILFROM=cron+$USER@server` resulting in `cron+maria@server` e-mail would be more clear than just `cron@server`.

**Comment by t8m** [comment]
PRs welcome

**Comment by thisHermit** [comment]
I am interested in working on it. Is it still relevant?

**Comment by lkraav** [comment]
> I am interested in working on it. Is it still relevant?

I'm definitely still interested in reaching this feature.

**Comment by thisHermit** [comment]
Hi @lkraav. I am a bit new to open source. So I didn't understand what you mean.

Do you intend to work on it or are you encouraging me to work on it?

**Comment by lkraav** [comment]
Ecnouraging you. I'm still very weak at C, as all my time is spent in scripting languages.

**Comment by fcappi** [comment]
Hi, as @lkraav I'm also interested in this feature.

@thisHermit are you still willing to work on this? If not, let me know and I can go ahead and implement it.

Thanks!

**Comment by fcappi** [comment]
Hi,

Now you can use environment variables(Using ${} or $ format) as part of MAILFROM and MAILTO. See the example below.

**Environment variable:**
```
[root@4e02e521cbe0 /]# env
HOSTNAME=4e02e521cbe0
```

**crontab:**
```
[root@4e02e521cbe0 /]# crontab -l
MAILTO=root-mailto@${HOSTNAME}
MAILFROM=root-mailfrom@$HOSTNAME
* * * * * /bin/bash /development/cronie/test.sh
```

**Email sent by cron:**
```
b'From: "(Cron Daemon)" <root-mailfrom@4e02e521cbe0>'
b'To: root-mailto@4e02e521cbe0'
b'Subject: Cron <root@4e02e521cbe0> echo "$(date)" >> /development/cronie/output.txt'
```

**_The feature should be included on next package release. For now, you have to build the code from master branch._**
