### ISSUE TITLE
cronie process doesn't finish when a mail can't be sent

### ISSUE THREAD

**Issue by kstreitova** [cronie-crond/cronie#27]
It can happen that a mail with the output of the job can't be sent (e.g. because of postfix misconfiguration). In that case, cron waits till the children process is finished which can cause that cron process doesn't quit and every time the cron job is repeated, a new process will be started and processes are piling up.

Maybe a timeout after that the waiting for the child process is ended could be a solution. What do you think? 

Thanks!

**Comment by t8m** [comment]
I do not think this is a right way. It is responsibility of the sysadmin to ensure that the cron jobs (or the mail jobs) finish properly. Killing the child jobs can have serious consequences and it is not even ensured that everything will be killed.

**Comment by kstreitova** [comment]
Hm, I guess that makes sense. Thank you for your reply.
