### ISSUE TITLE
Log when cronjob ends?

### ISSUE THREAD

**Issue by jayaich** [cronie-crond/cronie#48]
A problem which seems to crop up every so often is determining if a cron job has ended. I took a quick look to see if such an option was available, and found that an old Debian version of anacron supported the '-L' option. ('-L 2' would log when a job finished.) Looking further it seems that this option is still maintained in Debian 10, but is provided by a (somewhat large) patch applied to an older anacron. So basically this is a Debian extension.

I am curious as to why cronie does not seem to support the ability to log when jobs end. I would be willing to look into providing this ability (although probably not quite like the '-L' option. Using it on a Debian server the PID numbers were out of step, and made it a bit difficult to see when a job ended), but wondered if this idea had already been considered and rejected.

Thanks.

**Comment by t8m** [comment]
Do you want the logging in crond, anacron or both?

**Comment by jayaich** [comment]
I would have said both. Regardless of when the job started, via crond or anacron, it can be useful to know when it ends.

**Comment by t8m** [comment]
From top of my head I do not see any problem with adding such logging. Of course you might find that it would be too hard to find a right place for that code, but I would not expect that.

**Comment by jayaich** [comment]
Okay, a little confused here... are you asking me to do the coding or is it something you are going to do? I have no problem with taking a look at it, but when you asked where I wanted the logging I took it as something you were considering to do.

**Comment by t8m** [comment]
I could look at it eventually but if you want to help pull requests are always welcome.

**Comment by jayaich** [comment]
Okay, I'll take a look. I'll submit a PR when I have something (hopefully) usable.

**Comment by t8m** [comment]
This is already fixed.
