### ISSUE TITLE
'Content-Type' requires 'MIME-Version:' header too

### ISSUE THREAD

**Issue by ensc** [cronie-crond/cronie#5]
The generated mails are missing a `MIME-Version: 1.0` header which is mandatory for `Content-Type`.  E.g. RFC 2045 says

>    Messages composed in accordance with this document MUST include such
>    a header field, with the following verbatim text:
> 
>      MIME-Version: 1.0

Without this header, sendmail or either MTAs might reject cronjob notification mails with

>    554 5.6.1 Eight bit data not allowed

**Comment by t8m** [comment]
Fixed, thanks for the report.

**Comment by ensc** [comment]
afais, a similar patch is required for anacron too

**Comment by t8m** [comment]
Ah, of course you're right.
