### ISSUE TITLE
Wrong flag is set for weekly definition

### ISSUE THREAD

**Issue by nerg4l** [cronie-crond/cronie#52]
As far as I know `@weekly` means `0 0 * * 0`

At the moment `DOW_STAR` flag is set for this definition, but probably it wanted to be `DOM_STAR`. It is easy to miss that one letter difference.

https://github.com/cronie-crond/cronie/blob/master/src/entry.c#L182

**Comment by t8m** [comment]
Thank you for the report. It does not affect the job scheduling however cronnext display would be affected.
