### ISSUE TITLE
Backslashes in anacron commands are ignored unless at the end of the line (i.e. for continuation)

### ISSUE THREAD

**Issue by Ian2020** [cronie-crond/cronie#54]
When anacron parses a line in anacrontab it accidentally ignores any backslashes which are not followed by a newline and so they are removed from the command that is run. I came across this whilst trying to use the `-exec` action of the `find` command which requires a backslash semi-colon `\;` to terminate it correctly. 

As an example consider an anacrontab line such as:

```
1 0 report echo "Can you see these backslashes? \\\\"
```

The backslashes are never output. Looking in anacron/readtab.c, function read_tab_line looks like this:

```c
static char *
read_tab_line (void)
/* Read one line and return a pointer to it.
Return NULL if no more lines.
 */
{
    int c, prev=0;

    if (feof(tab)) return NULL;
    while (1)
    {
	c = getc(tab);
	if ((c == '\n' && prev != '\\') || c == EOF)
	{
	    if (0 != prev) obstack_1grow(&input_o, (char)prev);
	    break;
	}

	if ('\\' != prev && 0 != prev && '\n' != prev) obstack_1grow(&input_o, (char)prev);
	else if ('\n' == prev) obstack_1grow(&input_o, ' ');

	prev = c;
    }
    if (ferror(tab)) die_e("Error reading %s", anacrontab);
    obstack_1grow(&input_o, '\0');
    return obstack_finish(&input_o);
}
```

As far as I can tell whenever we examine a backslash i.e. `prev == '\\'` there's no way if can be added to input_o due to all the guards against it. So it just gets skipped over?

**Comment by t8m** [comment]
Fixed by a merged #55
