### ISSUE TITLE
Add a cronie task, it will automatically unlock

### ISSUE THREAD

**Issue by liquor1110** [cronie-crond/cronie#58]
step 1：crontab -e，create a task that executes every minute
step 2：Enter the wrong password multiple times during login，automatically lock for n minutes。
When the cronie task is executed, it will automatically unlock。

**Comment by t8m** [comment]
Which PAM module do you use for locking? What is your PAM configuration?

**Comment by t8m** [comment]
Also, this is not a bug in cronie but a bug in the PAM configuration. It should skip the locking PAM module in the account configuration for crond service.
So please report this against the software that provides the system PAM configuration.
