### ISSUE TITLE
Add option to validate crontab file

### ISSUE THREAD

**Issue by fcappi** [cronie-crond/cronie#59]
Hi guys,

I would like to propose the addition of a new option that would allow us to only validate the crontab file and do NOT update the user config.

This would be very helpful in scenarios where you want to validate the crontab before actually updating the user configuration.

Examples:
- crontab file is automatically generated, but the config updates will be applied in a later moment;
- user input validation on CI/CD pipelines;

Since the edit option already validates the file, I think it should be an easy change to add this feature, cause the validation logic is already in place.

What do you guys think about that?

If you agree, I would be glad to help, making the changes and submit a PR.

Suggestion:
```
crontab -v <crontab_file_path>
```
Thanks!

**Comment by t8m** [comment]
This is a good RFE proposal. If you want to work on a PR, please go ahead.
