### ISSUE TITLE
Error message for wrong or non specified user in /etc/crontab (RHBZ#1374264)

### ISSUE THREAD

**Issue by hhorak** [cronie-crond/cronie#68]
This was initially reported as https://bugzilla.redhat.com/show_bug.cgi?id=1374264

Description of problem:

Error message "ERROR (getpwnam() failed)" when no user specified for jobs in /etc/crontab is not
so helpful at the first.
Maybe it will be more nice to have something like "no/wrong user-name specified for this job", or similar.

Steps to Reproduce:
Put some job in /etc/crontab without "user-name"

*/1 * * * * echo "bla" > /tmp/bla

Actual results:

Error message : Error message "ERROR (getpwnam() failed)

Expected results:

Error message : no/wrong user-name specified for this job

--- Additional comment from Tomas Mraz on 2016-09-08 12:56:43 UTC ---

You've actually specified an user - user 'echo'.

And the user name is part of the message - see the 'echo' here:
Sep  8 14:53:01 vespa crond[1023]: (echo) ERROR (getpwnam() failed)

The reason why the getpwnam() failed can be various, it can be also that remote user identity server does not answer to queries.

So the message could be:
getpwnam() failed - user unknown or user identity resolution failure

--- Additional comment from Stefan Dordevic on 2016-09-08 13:13:33 UTC ---

(In reply to Tomas Mraz from comment #2)
> You've actually specified an user - user 'echo'.
> 
> And the user name is part of the message - see the 'echo' here:
> Sep  8 14:53:01 vespa crond[1023]: (echo) ERROR (getpwnam() failed)
> 

Yes, exactly. 

> The reason why the getpwnam() failed can be various, it can be also that
> remote user identity server does not answer to queries.
> 
> So the message could be:
> getpwnam() failed - user unknown or user identity resolution failure

It makes sense to me.

**Comment by t8m** [comment]
This is already fixed. The current message is getpwnam() failed - user unknown. See https://github.com/cronie-crond/cronie/commit/b836b5789cae7d608346d64e64ade121d8608518
