### ISSUE TITLE
0anacron fails to detect ac power is on

### ISSUE THREAD

**Issue by ovitters** [cronie-crond/cronie#69]
As reported at https://bugs.mageia.org/show_bug.cgi?id=27480:

> /etc/cron.hourly/0anacron checks for ac power indicator in
> /sys/class/power_supply/AC/online or /sys/class/power_supply/ADP{0..9}/online
> 
> The laptop in use uses
> /sys/class/power_supply/ACAD/online so cron.hourly assumes the laptop is on
> battery and never runs cron.daily, weekly, etc.

A patch was supplied but it won't apply to latest changes in master. It's a matter of adding ACAD as a path to check.

**Comment by t8m** [comment]
It is weird that the check would mean that such system is on battery as the default for the online value is 1. It could happen only in case there are other power supply devices present matching the above paths that are actually offline.

**Comment by t8m** [comment]
Can you please show output of

for i in /sys/class/power_supply/*/online ; do echo -n "$i: " ; cat $i; done

**Comment by t8m** [comment]
I made the script a little bit more general with 1.5.6 release. If it still doesn't work, please reopen.

**Comment by zlandau** [comment]
FYI I had this same problem, and at least for my case, the logic in d8490bbdc74a2a1aa98c4adc98d776101f512b1b seems reversed. First, my output:

```
# cat /sys/class/power_supply/axp288_charger/{type,online}
USB
0
```

This machine isn't powered by a battery at all, just AC. I'm guessing that power supply is for the USB ports or something. If change the battery check from `!= Batteryx` to `= Batteryx` then anacron runs. But I'm not sure if that was your intention or not.

```
    if [ `cat "$psupply/type" 2>/dev/null`x = Batteryx ] && [ -f "$psupply/online" ]; then
```

**Comment by t8m** [comment]
Hmm... that's bad. Of course the logic might not be reversed as that would break other cases.

**Comment by zlandau** [comment]
I'm not sure if it's useful, but there's also the 'present' flag which is 0 on that device. I'm not sure if devices with present=0 can just be skipped or not.

```
$ udevadm info --path=/sys/class/power_supply/axp288_charger
P: /devices/pci0000:00/808622C1:05/i2c-2/i2c-INT33F4:00/axp288_charger/power_supply/axp288_charger
L: 0
E: DEVPATH=/devices/pci0000:00/808622C1:05/i2c-2/i2c-INT33F4:00/axp288_charger/power_supply/axp288_charger
E: POWER_SUPPLY_NAME=axp288_charger
E: POWER_SUPPLY_TYPE=USB
E: POWER_SUPPLY_PRESENT=0
E: POWER_SUPPLY_ONLINE=0
E: POWER_SUPPLY_HEALTH=Unknown
E: POWER_SUPPLY_CONSTANT_CHARGE_CURRENT=1200000
E: POWER_SUPPLY_CONSTANT_CHARGE_CURRENT_MAX=1200000
E: POWER_SUPPLY_CONSTANT_CHARGE_VOLTAGE=4200000
E: POWER_SUPPLY_CONSTANT_CHARGE_VOLTAGE_MAX=4200000
E: POWER_SUPPLY_INPUT_CURRENT_LIMIT=1500000
E: SUBSYSTEM=power_supply
```
