### ISSUE TITLE
autogen.sh fails on autoconf 2.69c

### ISSUE THREAD

**Issue by trofi** [cronie-crond/cronie#70]
It's a forward of downstream https://bugs.gentoo.org/750728 where `cronie` fails on `autoconf-2.69c` (soon to be `autoconf-2.70`).

```
$ ./autogen.sh
/usr/bin/m4:configure.ac:1: Warning: excess arguments to builtin `m4_define' ignored
autom4te-2.70_beta2: error: /usr/bin/m4 failed with exit status: 1
aclocal-1.16: error: echo failed with exit status: 1
autogen.sh: exit on error
```

It happens because `autoconf-2.70` slightly changed quotation around `AC_INIT` and fails more prominently if there is not just an email address. The following workaround seems to fix it:

```diff
--- a/configure.ac
+++ b/configure.ac
@@ -1,4 +1,4 @@
-AC_INIT([cronie],[1.5.5],[mmaslano@redhat.com,tmraz@fedoraproject.org])
+AC_INIT([cronie],[1.5.5],[mmaslano@redhat.com])
 AC_CONFIG_HEADER([config.h])
 AC_PREREQ(2.60)
```

**Comment by t8m** [comment]
Fixed, dropping the e-mail altogether. Thank you for the report.
