### ISSUE TITLE
Is this possible racing condition?

### ISSUE THREAD

**Issue by hytgbn** [cronie-crond/cronie#73]
I recently found one of my host doesn't run specific cronjob file. The cronjob file is written when the host gets launched. (As part of UserData of AWS EC2 instance).

host: Amazon linux 4.14 assuming this supports inotify

Wondering if this race condition is ever possible:

1. crond loads database without the cronjob file (or when the file doesn't have content) https://github.com/cronie-crond/cronie/blob/master/src/cron.c#L319
2. Then the cronjob content is written.
3. crond adds inotify watch https://github.com/cronie-crond/cronie/blob/master/src/cron.c#L333

If this is ever possible, would it make sense to do load_database after adds watch?

**Comment by t8m** [comment]
What is the cronie version on the system? There were some other possible races solved before.
But yes, it the job file is written simultaneously with crond startup I think the race you described above is possible and easy fix should be to just switch the order of the initial database load and watch setup.

**Comment by t8m** [comment]
Fixed with the PR #74
