### ISSUE TITLE
No way to disable colour output of crontab -l

### ISSUE THREAD

**Issue by jwakely** [cronie-crond/cronie#81]
As noted at https://bugzilla.redhat.com/show_bug.cgi?id=1838180

> there should be at least some way to disable all colorization for the tool itself.  at a system level, redhat has "COLOR none" in /etc/DIR_COLORS for ls which stops "--color=auto" alias from activating.  there is also a no-color initiative at https://no-color.org/

You can do `crontab -l | cat` but I agree with the bug reporter that a way to disable the colours through config would be preferable. Even just a `--no-color` option would be an improvement.

**Comment by t8m** [comment]
Adding an option would be an overkill. But supporting NO_COLOR environment variable is IMO worth it. I'll do that.

**Comment by jwakely** [comment]
Thanks! Yes, I agree a new option that is only useful for the `-l` option doesn't make much sense.

**Comment by t8m** [comment]
Fixed in 765a745c6497f
