### ISSUE TITLE
anacron doesn't run jobs when HID battery is present

### ISSUE THREAD

**Issue by jsullivan3** [cronie-crond/cronie#83]
My Fedora 33 system updated its cronie-anacron package to 1.5.6 yesterday, and my daily cron jobs did not fire this morning.

The `/etc/cron.hourly/0anacron` file queries all power supplies to determine if any have AC power as of commit https://github.com/cronie-crond/cronie/commit/ba79defe39af763a15155b65d2066a78180fd601.  However, this particular system is an old iMac without a battery, though it does have a Bluetooth mouse which registers its battery in `/sys/class/power_supply/hidpp_battery_0`:

```
Device: /org/freedesktop/UPower/devices/mouse_hidpp_battery_0
  native-path:          hidpp_battery_0
  model:                M305
  serial:               101f-97-e9-79-7e
  power supply:         no
  updated:              Sun 21 Mar 2021 08:53:25 AM EDT (65 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               unknown
    warning-level:       none
    battery-level:       unknown
    percentage:          50% (should be ignored)
    icon-name:          'battery-missing-symbolic'
```
This mouse battery device is causing the anacron jobs to not run.

**Comment by t8m** [comment]
Could you please show me the output of `ls -lR /sys/class/power_supply` on your system? And also the contents of online and type files in each of the power_supply devices.

**Comment by jsullivan3** [comment]
Sure can!

Here is the output of the commands you requested plus information about the kernel and cronie versions from the system on which I observed the issue:

```
$ ls -lR /sys/class/power_supply
/sys/class/power_supply:
total 0
lrwxrwxrwx. 1 root root 0 Mar 22 08:07 hidpp_battery_0 -> ../../devices/pci0000:00/0000:00:1a.7/usb1/1-1/1-1.3/1-1.3:1.1/0003:046D:C52F.0003/0003:046D:101F.0008/power_supply/hidpp_battery_0
$ for psupply in /sys/class/power_supply/* ; do for prop in ${psupply}/type ${psupply}/online ; do echo -n "${prop}: " ; if [ -e ${prop} ] ; then cat ${prop} ; else echo "does not exist" ; fi ; done ; done
/sys/class/power_supply/hidpp_battery_0/type: Battery
/sys/class/power_supply/hidpp_battery_0/online: 0
$ uname -r
5.11.7-200.fc33.x86_64
$ rpm -q cronie cronie-anacron
cronie-1.5.6-1.fc33.x86_64
cronie-anacron-1.5.6-1.fc33.x86_64
```

For comparison, here is the output from a laptop that has a similar Bluetooth mouse with dongle, but also contains an internal battery:

```
$ ls -lR /sys/class/power_supply
/sys/class/power_supply:
total 0
lrwxrwxrwx. 1 root root 0 Mar 22 08:16 AC0 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/ACPI0003:00/power_supply/AC0
lrwxrwxrwx. 1 root root 0 Mar 22 08:16 BAT0 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/PNP0C0A:00/power_supply/BAT0
lrwxrwxrwx. 1 root root 0 Mar 22 08:16 hidpp_battery_0 -> ../../devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.3/2-1.3:1.1/0003:046D:C534.0003/0003:046D:4075.0004/power_supply/hidpp_battery_0
$ for psupply in /sys/class/power_supply/* ; do for prop in ${psupply}/type ${psupply}/online ; do echo -n "${prop}: " ; if [ -e ${prop} ] ; then cat ${prop} ; else echo "does not exist" ; fi ; done ; done
/sys/class/power_supply/AC0/type: Mains
/sys/class/power_supply/AC0/online: 0
/sys/class/power_supply/BAT0/type: Battery
/sys/class/power_supply/BAT0/online: does not exist
/sys/class/power_supply/hidpp_battery_0/type: Battery
/sys/class/power_supply/hidpp_battery_0/online: 0
$ uname -r
5.11.7-200.fc33.x86_64
$ rpm -q cronie cronie-anacron
cronie-1.5.6-1.fc33.x86_64
cronie-anacron-1.5.6-1.fc33.x86_64
```

**Comment by jsullivan3** [comment]
I am testing a change that ignores power supplies that begin with `hidpp`, and also adds an `/etc/sysconfig/anacron` file which contains a setting that will allow a user to specify the behavior of anacron when the system is running on battery.  The change seems to address this particular issue, though I haven't run through the RPM build process to ensure I correctly updated the packaging.

If this change sounds amenable to you, I'd be happy to create a PR once I've verified the correctness of the RPM build process.

**Comment by t8m** [comment]
Perhaps we should just skip those which contain type of Battery?

**Comment by jsullivan3** [comment]
I can see the logic with that approach...or would it make sense to be more conservative and check the `online` value for power supplies of type `Mains`?  I can see an argument either way - both approaches would address the issue I saw.  I'm trying to consider other scenarios, though.

**Comment by jsullivan3** [comment]
And, both approaches are much better than the original approach I took of parsing the file name.  I'm going to modify my original change to verify this suggestion.  Thank you!

**Comment by t8m** [comment]
> I can see the logic with that approach...or would it make sense to be more conservative and check the `online` value for power supplies of type `Mains`? I can see an argument either way - both approaches would address the issue I saw. I'm trying to consider other scenarios, though.

I think this could be problematic with USB PD devices and so on. They might have different type than Mains and still be the real power supply of the device. I imagine a laptop with both Mains and USB PD power supply lines which would appear to be offline if it is connected to power through USB PD and not the regular power input.

**Comment by t8m** [comment]
So apparently I am wrong and only Mains power supply types should be considered. I've adjusted the code accordingly.
