### ISSUE TITLE
RFE: Do not send mail if the job was successful

### ISSUE THREAD

**Issue by khardix** [cronie-crond/cronie#89]
This is a continuation of https://github.com/cronie-crond/cronie/pull/80, which I closed by accident – sorry about that.

> I dislike this being a new optional field in the cron entry.

I'm also not thrilled from the new field, *but* it would be compatible with \*BSD cron implementations, as linked in the original PR: https://github.com/NetBSD/src/commit/666eac5018f695be8449458fffd3de77d9305eb1.

> I'd prefer something similar to the - at the beginning of the entry that switches off the logging (for root only).
Or perhaps the suggestion from: https://bugzilla.redhat.com/show_bug.cgi?id=1591763#c11

I will forward the suggestions to the original requester and see what they think. Hopefully I can also persuade them to continue the discussion here, so it is present in one place.

--

In the mean time, thanks for all the feedback so far, Tomas!

**Comment by job** [comment]
> I'm also not thrilled from the new field, _but_ it would be compatible with *BSD cron implementations, as linked in the original PR: [NetBSD/src@666eac5](https://github.com/NetBSD/src/commit/666eac5018f695be8449458fffd3de77d9305eb1).

FreeBSD also adopted the option: https://github.com/freebsd/freebsd-src/commit/5b80de237b53fd14e3926dd58fc0b78be983ed84 (copied from OpenBSD)

**Comment by t8m** [comment]
If someone submits a PR with the `-n` flag support, I'll consider it.
