### ISSUE TITLE
"path too long" error when hostname is long

### ISSUE THREAD

**Issue by GeertJohan** [cronie-crond/cronie#9]
It looks like crontab throws a "path too long" error when the hostname of the machine on which the cmd is executed has a large value.
https://github.com/cronie-crond/cronie/blob/master/src/crontab.c#L756

**Comment by t8m** [comment]
Which system is this on? Also can you give an example of the hostname? The full path limit should 4096 bytes on Linux and that should be fairly sufficient.

**Comment by t8m** [comment]
No requested information provided. Closing.
