### ISSUE TITLE
Limit for the number of crontab entries is too low

### ISSUE THREAD

**Issue by kstreitova** [cronie-crond/cronie#91]
Hello,

In commit a6576769f01325303b11edc3e0cfb05ef382ce56 you've created a limit for crontab entries (1000) to prevent DoS attack. However some of our customers and other users are hitting this limit in some reasonable edge cases. Debian has already [patched](https://launchpad.net/debian/+source/cron/+changelog) this limit to 10 000 entries in 2019:

> cron (3.0pl1-134) unstable; urgency=medium
> 
>   * Increase maximum crontab length to 10,000 lines.
>     The previous limit proved to be too low for users with edge cases.
>     (Closes: #925276)

I would like to ask if you had any particular reason for 1000 entries and if you think that it would be safe to change it 10 000.

Thank you!

**Comment by t8m** [comment]
I would not oppose to raising the limit to 10000 cron entries, please submit a PR. I'd keep the environment at 1000 max entries.
